apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-world-stateful
spec:
  serviceName: "hello-world-stateful"
  selector:
    matchLabels:
      app: hello-world-stateful
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world-stateful
    spec:
      containers:
      - name: hello-world-stateful
        image: dors-hello-world
        imagePullPolicy: IfNotPresent
        env:
          - name: "DORS_HOME"
            value: "/data"
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Mi
